BeautyBar_env/BeautyBar/BeautyBar/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bar.urls', namespace='bar'))
]

BeautyBar_env/BeautyBar/bar/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BeautyBar_env/BeautyBar/bar/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    
    def get_absolute_url(self):
        return reverse('bar:ProductListByCategory', args=[self.slug])

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name="Изображение услуги")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    master = models.CharField(max_length=200, db_index=True, verbose_name="Мастер")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):
          return reverse('bar:ProductDetail', args=[self.id, self.slug])

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

BeautyBar_env/BeautyBar/bar/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Страница с услугами
def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'bar/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'bar/product/detail.html', {'product': product}) 

BeautyBar_env/BeautyBar/bar/templates/bar/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <!-- Styles -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
  <section id="header">
    <div class="top container">
      Салон красоты
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">Вы не записались ни на одну услугу</div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
    {% block content %}{% endblock %}
  </section>
</body>
</html>

BeautyBar_env/BeautyBar/bar/templates/bar/product/detail.html
{% extends "bar/base.html" %}

{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
  <div class="product-detail">
    <div class="col-sm-4">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
    </div>
    <div class="col-sm-8">
      <h1>{{ product.name }}</h1>
      <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
      <p class="price">
        {{ product.price }} руб.
      </p>
      <span>
        {{ product.description | linebreaks}}
      </span>
    </div>
  </div>
{% endblock %}

BeautyBar_env/BeautyBar/bar/templates/bar/product/list.html
{% extends 'bar/base.html' %}

{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница услуг {% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url "bar:ProductList" %}">Все</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
          <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="items row">
      {% for product in products %}
        <div class="item col-sm-4">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          {{ product.price }} руб.
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}</code>
</pre>